//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.SuccessMessages", typeof(SuccessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment was added to content successful.
        /// </summary>
        public static string AddCommentToContentSuccessful {
            get {
                return ResourceManager.GetString("AddCommentToContentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lables was added to content successful.
        /// </summary>
        public static string AddLablesToContentSuccessful {
            get {
                return ResourceManager.GetString("AddLablesToContentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lable was added successful.
        /// </summary>
        public static string AddLableSuccessful {
            get {
                return ResourceManager.GetString("AddLableSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The addition was successful.
        /// </summary>
        public static string AddSuccessful {
            get {
                return ResourceManager.GetString("AddSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The avatar image was deleted successful.
        /// </summary>
        public static string DeleteAvatarImageSuccessful {
            get {
                return ResourceManager.GetString("DeleteAvatarImageSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment was deleted from content successful.
        /// </summary>
        public static string DeleteCommentFromContentSuccessful {
            get {
                return ResourceManager.GetString("DeleteCommentFromContentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content was deleted successful.
        /// </summary>
        public static string DeleteContentSuccessful {
            get {
                return ResourceManager.GetString("DeleteContentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The favorite post was deleted successful.
        /// </summary>
        public static string DeleteFavoritePostSuccessful {
            get {
                return ResourceManager.GetString("DeleteFavoritePostSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lable was deleted from content successful.
        /// </summary>
        public static string DeleteLableFromContentSuccessful {
            get {
                return ResourceManager.GetString("DeleteLableFromContentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lable was deleted successful.
        /// </summary>
        public static string DeleteLableSuccessful {
            get {
                return ResourceManager.GetString("DeleteLableSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The music kind was deleted successful.
        /// </summary>
        public static string DeleteMusicKindSuccessful {
            get {
                return ResourceManager.GetString("DeleteMusicKindSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification was deleted successful.
        /// </summary>
        public static string DeleteNotificationSuccessful {
            get {
                return ResourceManager.GetString("DeleteNotificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The play list post was deleted successful.
        /// </summary>
        public static string DeletePlayListPostSuccessful {
            get {
                return ResourceManager.GetString("DeletePlayListPostSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The play list was deleted successful.
        /// </summary>
        public static string DeletePlayListSuccessful {
            get {
                return ResourceManager.GetString("DeletePlayListSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post was deleted successful.
        /// </summary>
        public static string DeletePostSuccessful {
            get {
                return ResourceManager.GetString("DeletePostSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post type was deleted successful.
        /// </summary>
        public static string DeletePostTypeSuccessful {
            get {
                return ResourceManager.GetString("DeletePostTypeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was deleted successful.
        /// </summary>
        public static string DeleteUserSuccessful {
            get {
                return ResourceManager.GetString("DeleteUserSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word was deleted successful.
        /// </summary>
        public static string DeleteWordSuccessful {
            get {
                return ResourceManager.GetString("DeleteWordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exam processing successful.
        /// </summary>
        public static string ExamProcessingSuccessful {
            get {
                return ResourceManager.GetString("ExamProcessingSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The load content was successful.
        /// </summary>
        public static string LoadContentSuccessful {
            get {
                return ResourceManager.GetString("LoadContentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The load exam was successful.
        /// </summary>
        public static string LoadExamSuccessfull {
            get {
                return ResourceManager.GetString("LoadExamSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The load notifications was successful.
        /// </summary>
        public static string LoadNotificationsSuccessfull {
            get {
                return ResourceManager.GetString("LoadNotificationsSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The load contents was successful.
        /// </summary>
        public static string LoadRelatedContentsSuccessful {
            get {
                return ResourceManager.GetString("LoadRelatedContentsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The users was loaded successful.
        /// </summary>
        public static string LoadUsersSuccessfull {
            get {
                return ResourceManager.GetString("LoadUsersSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was loaded successful.
        /// </summary>
        public static string LoadUserSuccessfull {
            get {
                return ResourceManager.GetString("LoadUserSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The load word was successful.
        /// </summary>
        public static string LoadWordSuccessfull {
            get {
                return ResourceManager.GetString("LoadWordSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login was successful.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification was sent successfully.
        /// </summary>
        public static string NotificationSentSuccessful {
            get {
                return ResourceManager.GetString("NotificationSentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post was uploaded successful.
        /// </summary>
        public static string PostUploadSuccessful {
            get {
                return ResourceManager.GetString("PostUploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token revoked.
        /// </summary>
        public static string RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("RefreshTokenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token was successful.
        /// </summary>
        public static string RefreshTokenSuccessfull {
            get {
                return ResourceManager.GetString("RefreshTokenSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The register was successful.
        /// </summary>
        public static string RegisterSuccessful {
            get {
                return ResourceManager.GetString("RegisterSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was successful.
        /// </summary>
        public static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user was banned successful.
        /// </summary>
        public static string UserBannedSuccessful {
            get {
                return ResourceManager.GetString("UserBannedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user was unbanned successful.
        /// </summary>
        public static string UserUnbannedSuccessful {
            get {
                return ResourceManager.GetString("UserUnbannedSuccessful", resourceCulture);
            }
        }
    }
}
