global using Domain;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Softmax.Abstraction.DICommon;
global using Softmax.Utilities.Validation;
global using System;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
